name = "gleam_otp"
version = "1.3.0"
licences = ["Apache-2.0"]
description = "Fault tolerant multi-core programs with OTP, the BEAM actor framework."

gleam = ">= 1.11.0"

internal_modules = [
  "gleam/otp/internal/*"
]

repository = { type = "github", user = "gleam-lang", repo = "otp" }
links = [
  { title = "Website", href = "https://gleam.run" },
  { title = "Sponsor", href = "https://github.com/sponsors/lpil" },
]

[dependencies]
gleam_stdlib = { path = "../gleam-native-stdlib" }
gleam_erlang = { path = "../gleam-native-erlang" }

[dev-dependencies]
gleeunit = { path = "../gleam-native-gleeunit" }
