# Do not manually edit this file, it is managed by Gleam.
#
# This file locks the dependency versions used, to make your build
# deterministic and to prevent unexpected versions from being included
# in your application.
#
# You should check this file into your source control repository.

packages = [
  { name = "gleam_erlang", version = "1.3.0", build_tools = ["gleam"], requirements = ["gleam_stdlib"], source = "local", path = "../gleam-native-erlang" },
  { name = "gleam_stdlib", version = "1.0.5", build_tools = ["gleam"], requirements = [], source = "local", path = "../gleam-native-stdlib" },
  { name = "gleeunit", version = "1.11.0", build_tools = ["gleam"], requirements = ["gleam_stdlib"], source = "local", path = "../gleam-native-gleeunit" },
]

[requirements]
gleam_erlang = { path = "../gleam-native-erlang" }
gleam_stdlib = { path = "../gleam-native-stdlib" }
gleeunit = { path = "../gleam-native-gleeunit" }
